image: docker:latest
services:
  - docker:dind
  - mongo
stages:
  - build
  - package
variables:
  DOCKER_TLS_CERTDIR: ""
build:
  image: gradle:6.5.1-jdk11
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar
package:
  stage: package
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#todo deploy on server -> now I use docker compose file on server