version: '3'
services:
  udemy-reactor:
    container_name: udemy-reactor
    image: registry.gitlab.com/artur.gitlab/udemyreactor:develop
    networks:
      - reactor
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
networks:
  reactor:
