spring:
  profiles:
    active: test
simple:
  client: http://localhost:8080
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: test
---
spring:
  profiles:
    active: docker
  data:
    mongodb:
      uri: mongodb://user:user@mongodb1:27017,mongodb2:27018,mongodb3:27019/shopdb
